# Generated by Django 5.2.1 on 2026-01-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_usuario_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdCondominio', models.IntegerField()),
                ('NomeCondominio', models.CharField(max_length=255)),
                ('Unidade', models.CharField(max_length=50)),
                ('Contato', models.CharField(max_length=255)),
                ('Cobranca', models.IntegerField()),
                ('DescricaoTaxa', models.CharField(max_length=255)),
                ('Complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('Geracao', models.DateField()),
                ('Vencimento', models.DateField()),
                ('Liquidacao', models.DateField(blank=True, null=True)),
                ('Credito', models.DateField(blank=True, null=True)),
                ('FormaPagamento', models.CharField(blank=True, max_length=100, null=True)),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
