# Generated by Django 5.2.1 on 2026-02-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_receitas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Condominio', models.CharField(max_length=255)),
                ('Vencimento', models.DateField()),
                ('Liquidacao', models.DateField(blank=True, null=True)),
                ('Fornecedor', models.CharField(max_length=255)),
                ('Categoria', models.CharField(max_length=255)),
                ('Complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('Documento', models.CharField(max_length=100)),
                ('Competencia', models.DateField()),
                ('FormaPagamento', models.CharField(blank=True, max_length=100, null=True)),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
